import Toybox.Application;
import Toybox.Complications;
import Toybox.Graphics;
import Toybox.Lang;
import Toybox.Math;
import Toybox.System;
import Toybox.WatchUi;

// Garmin's native watch-face editor (Toybox.Application.WatchFaceConfig, API 5.1+: vivoactive 6,
// fenix 8, FR570/970, Venu 4, ...) and long-press-to-open-app for every device.
// The options come from resources/configs/watchface.xml (generated by tools/gen_meridian_settings.py):
//   style 0 = "Phone app" (default: phone Background/Time font/Frame), style id = 1 + theme*12 + font*3 + frame,
//   accent color = time digits, data color = data text,
//   data color White (default) = auto,
//   complication uniqueIdentifier 1..8 = SlotTop, SlotLeft, SlotRight, SlotBottom, ArcTL, ArcTR, ArcBL, ArcBR.
// Precedence: a value set in the native editor (non-null and not one of the "auto" defaults) overrides
// the phone setting for those items; everything else stays phone-settings only.
// Devices without WatchFaceConfig: unchanged (the phone settings / on-watch Menu2 only).
module Native {

    // Apply the editor's settings over the phone settings already loaded into the view.
    // cfg: the settings being edited (edit mode), or null for the active ones.
    function apply(v as MeridianView, cfg) as Void {
        if (!(Application has :WatchFaceConfig)) { return; }
        var st = cfg;
        if (st == null) {
            try {
                st = Application.WatchFaceConfig.getSettings(null);
            } catch (e) {
                st = null;
            }
        }
        if (st == null) { return; }
        st = st as Application.WatchFaceConfig.Settings;
        var sid = st.styleId;
        if (sid != null && sid >= 1 && sid <= 60) {
            v.mTheme = (sid - 1) / 12;
            v.mStyle = ((sid - 1) % 12) / 3;
            v.mFrame = (sid - 1) % 3;
        }
        var ac = st.accentColor;
        if (ac != null && ac.color != null) {
            v.mHourC = (ac.color as Number) & 0xFFFFFF;
            v.mMinC = v.mHourC;
        }
        var dcol = st.complicationColor;
        if (dcol != null && dcol.color != null) {
            var c = (dcol.color as Number) & 0xFFFFFF;
            if (c != 0xFFFFFF) { v.mTextC = c; }   // White (the default) = auto: keep the phone/theme color
        }
        var cs = st.complicationSettings;
        if (cs == null) { return; }
        for (var i = 0; i < cs.size(); i++) {
            var c = cs[i];
            var uid = c.uniqueIdentifier;
            var id = c.complicationId;
            if (uid == null || uid < 1 || uid > 8 || id == null) { continue; }
            var k = uid - 1;
            var opt = MD.fromComp(id.getType() as Number);
            v.mIds[k] = id;
            if (k < 4) {
                v.mSlots[k] = opt;
            } else {
                v.mArcs[k - 4] = opt;
            }
        }
    }

    // Device px per design unit.
    function scale() as Float {
        return System.getDeviceSettings().screenWidth / 390.0;
    }

    // Slot under a touch point (device px): 0..3 circles, 4..7 arcs, -1 none.
    function slotAt(px as Number, py as Number, v as MeridianView) as Number {
        var k = scale();
        var x = px / k;
        var y = py / k;
        for (var i = 0; i < 4; i++) {
            var ddx = x - v.SLOT_X[i];
            var ddy = y - v.SLOT_Y[i];
            if (ddx * ddx + ddy * ddy <= (v.CIRCLE_R + 6) * (v.CIRCLE_R + 6)) { return i; }
        }
        var rx = x - v.CX;
        var ry = y - v.CY;
        var r = Math.sqrt(rx * rx + ry * ry);
        if (r < 118) { return -1; }
        var a = Math.toDegrees(Math.atan2(rx, -ry));   // clock degrees
        if (a < 0) { a += 360; }
        for (var i = 0; i < 4; i++) {
            if (a >= v.ARC_A[i] - 4 && a <= v.ARC_B[i] + 4) { return i + 4; }
        }
        return -1;
    }

    // Bounding box (device px, clipped to the screen) of slot k as drawn: the circle (or hexagon)
    // with its frame; for an arc the track, fill, riding icon and the value text along it.
    function box(k as Number, v as MeridianView) as Graphics.BoundingBox {
        var s = scale();
        var x0 = 390.0;
        var y0 = 390.0;
        var x1 = 0.0;
        var y1 = 0.0;
        if (k < 4) {
            var r = v.CIRCLE_R + 5;
            x0 = v.SLOT_X[k] - r;
            x1 = v.SLOT_X[k] + r;
            y0 = v.SLOT_Y[k] - r;
            y1 = v.SLOT_Y[k] + r;
        } else {
            var i = k - 4;
            var radii = [v.ARC_TEXT_R[i] - 19, v.ARC_R + 20];
            for (var a = v.ARC_A[i] - 6; a <= v.ARC_B[i] + 6; a += 3) {
                var rad = Math.toRadians(a);
                for (var j = 0; j < 2; j++) {
                    var px = v.CX + radii[j] * Math.sin(rad);
                    var py = v.CY - radii[j] * Math.cos(rad);
                    if (px < x0) { x0 = px; }
                    if (px > x1) { x1 = px; }
                    if (py < y0) { y0 = py; }
                    if (py > y1) { y1 = py; }
                }
            }
        }
        if (x0 < 0) { x0 = 0.0; }
        if (y0 < 0) { y0 = 0.0; }
        if (x1 > 390) { x1 = 390.0; }
        if (y1 > 390) { y1 = 390.0; }
        var b = new Graphics.BoundingBox();
        var bx = Math.floor(x0 * s).toNumber();
        var by = Math.floor(y0 * s).toNumber();
        b.addRectangle(bx, by, Math.ceil(x1 * s).toNumber() - bx, Math.ceil(y1 * s).toNumber() - by);
        return b;
    }

    // Complication behind slot k (to open its Garmin app), or null.
    function compId(k as Number, v as MeridianView) as Complications.Id or Null {
        if (!(Toybox has :Complications)) { return null; }
        var id = v.mIds[k];
        if (id != null) { return id as Complications.Id; }
        var opt = k < 4 ? v.mSlots[k] : v.mArcs[k - 4];
        if (opt < 0 || opt >= MD.TO_COMP.size()) { return null; }
        var t = MD.TO_COMP[opt];
        return t == 0 ? null : new Complications.Id(t as Complications.Type);
    }
}

// One slot drawn alone, handed to the editor to highlight/animate the selected complication.
class MeridianSlotDrawable extends WatchUi.Drawable {
    var mView as MeridianView;
    var mK as Number;

    function initialize(view as MeridianView, k as Number, b as Graphics.BoundingBox) {
        Drawable.initialize({:locX => b.x, :locY => b.y, :width => b.width, :height => b.height});
        mView = view;
        mK = k;
    }

    function draw(dc as Graphics.Dc) as Void {
        mView.drawOne(dc, mK);
    }
}

class MeridianDelegate extends WatchUi.WatchFaceDelegate {
    var mView as MeridianView;

    function initialize(view as MeridianView) {
        WatchFaceDelegate.initialize();
        mView = view;
    }

    // Editor changed something: re-read that config and redraw. The edited slot stays hidden
    // only while a complication is being picked (the system draws our drawable instead).
    function onWatchFaceConfigEdited(options) as Void {
        var id = options[:configId];
        if (id != null && (Application has :WatchFaceConfig)) {
            var st = Application.WatchFaceConfig.getSettings(id);
            if (st != null) { mView.mCfg = st; }
        }
        if (options[:type] != 1) {   // 1 = WatchUi.WATCH_FACE_CONFIG_TYPE_COMPLICATION
            mView.mHide = -1;
        }
        mView.loadSettings();
        WatchUi.requestUpdate();
    }

    function getComplicationDrawable(ref) {
        var uid = ref.uniqueIdentifier;
        if (uid == null || uid < 1 || uid > 8) { return null; }
        var k = (uid as Number) - 1;
        mView.mHide = k;
        WatchUi.requestUpdate();
        var b = Native.box(k, mView);
        return new WatchUi.ComplicationDrawableRef({
            :drawable => new MeridianSlotDrawable(mView, k, b),
            :boundingBox => b
        });
    }

    // Edit mode: tapping a field selects it in the editor.
    function onTap(ev as WatchUi.ClickEvent) as Boolean {
        if (!mView.mEdit) { return false; }
        var c = ev.getCoordinates();
        var k = Native.slotAt(c[0], c[1], mView);
        if (k < 0) { return false; }
        setSelectedComplication(k + 1);
        return true;
    }

    // Normal mode: touch and hold a field opens the related Garmin app (steps, heart rate, ...).
    function onPress(ev as WatchUi.ClickEvent) as Boolean {
        var c = ev.getCoordinates();
        var k = Native.slotAt(c[0], c[1], mView);
        if (mView.mEdit || !(Complications has :exitTo)) { return false; }
        if (k < 0) { return false; }
        var id = Native.compId(k, mView);
        if (id == null) { return false; }
        try {
            Complications.exitTo(id);
        } catch (e) {
            return false;
        }
        return true;
    }
}
