// GENERATED by tools/gen_meridian_settings.py - do not edit.
import Toybox.Lang;

module MenuData {

    function groupTitles() as Array<String> {
        return ["Data fields", "Style", "Time colors", "Colors", "Arc colors"];
    }

    // Per group: [key, title, list id (-1 = on/off toggle)]
    function groupItems(g as Number) as Array<Array> {
        if (g == 0) { return [["SlotTop", "Top circle", 0], ["SlotLeft", "Left circle", 0], ["SlotRight", "Right circle", 0], ["SlotBottom", "Bottom circle", 0], ["ArcTL", "Top-left arc", 0], ["ArcTR", "Top-right arc", 0], ["ArcBL", "Bottom-left arc", 0], ["ArcBR", "Bottom-right arc", 0]]; }
        if (g == 1) { return [["Theme", "Background", 1], ["FontStyle", "Time font", 2], ["Frame", "Data field frame", 3], ["TimeFormat", "Time format", 4], ["LeadingZero", "Leading zero on hour", -1]]; }
        if (g == 2) { return [["HourColor", "Hour color", 5], ["MinuteColor", "Minute color", 5]]; }
        if (g == 3) { return [["WeekdayColor", "Weekday / label color", 6], ["TextColor", "Data text color", 6], ["IconColor", "Circle icon color", 7], ["OutlineColor", "Data field frame color", 6], ["TrackColor", "Arc track color", 6]]; }
        if (g == 4) { return [["ArcColorTL", "Top-left arc color", 7], ["ArcColorTR", "Top-right arc color", 7], ["ArcColorBL", "Bottom-left arc color", 7], ["ArcColorBR", "Bottom-right arc color", 7]]; }
        return [];
    }

    function labels(id as Number) as Array<String> {
        if (id == 0) { return ["None", "Steps", "Steps % of goal", "Distance", "Calories", "Intensity minutes (week)", "Heart rate", "Resting heart rate", "Body Battery", "Stress", "Pulse Ox (SpO2)", "Respiration", "Battery %", "Battery days left", "Temperature", "Weather (condition + temp)", "High / low temp", "Precipitation chance", "Humidity", "Wind speed", "UV index", "Sunrise", "Sunset", "Next sunrise/sunset", "Notifications", "Alarms", "Phone connection", "Date", "Week number", "Altitude", "Recovery time", "Training status", "VO2 max (run)", "Sleep score", "Next calendar event", "Floors climbed", "Sea level pressure"]; }
        if (id == 1) { return ["Black", "Navy", "Charcoal", "Cream", "White"]; }
        if (id == 2) { return ["Rounded", "Square", "Serif", "Classic"]; }
        if (id == 3) { return ["Circle", "Hexagon", "None"]; }
        if (id == 4) { return ["Follow watch", "12-hour", "24-hour"]; }
        if (id == 5) { return ["Auto (theme)", "White", "Cream", "Silver", "Grey", "Dark grey", "Lime", "Green", "Mint", "Teal", "Sky", "Blue", "Steel blue", "Lavender", "Pink", "Coral", "Peach", "Orange", "Gold", "Yellow", "Red", "Brick red", "Deep teal", "Navy", "Black", "Gradient white to silver", "Gradient lime to teal", "Gradient lime to pale green", "Gradient lime to sky", "Gradient pink to orange", "Gradient sky to lavender", "Gradient gold to red", "Gradient teal to blue"]; }
        if (id == 6) { return ["Auto (theme)", "White", "Cream", "Silver", "Grey", "Dark grey", "Lime", "Green", "Mint", "Teal", "Sky", "Blue", "Steel blue", "Lavender", "Pink", "Coral", "Peach", "Orange", "Gold", "Yellow", "Red", "Brick red", "Deep teal", "Navy", "Black"]; }
        if (id == 7) { return ["Auto (theme)", "Dynamic (follows value)", "White", "Cream", "Silver", "Grey", "Dark grey", "Lime", "Green", "Mint", "Teal", "Sky", "Blue", "Steel blue", "Lavender", "Pink", "Coral", "Peach", "Orange", "Gold", "Yellow", "Red", "Brick red", "Deep teal", "Navy", "Black"]; }
        return [];
    }

    function values(id as Number) as Array<Number> {
        if (id == 0) { return [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]; }
        if (id == 1) { return [0, 1, 2, 3, 4]; }
        if (id == 2) { return [0, 1, 2, 3]; }
        if (id == 3) { return [0, 1, 2]; }
        if (id == 4) { return [0, 1, 2]; }
        if (id == 5) { return [-1, 16777215, 16051939, 12434877, 9079434, 4868682, 13038642, 6021467, 7268279, 3003583, 11129855, 5088255, 8367840, 12170485, 16727461, 16743019, 16107173, 16754219, 16761370, 16769306, 16726862, 11747630, 2051679, 1780292, 1118481, -2, -3, -4, -5, -6, -7, -8, -9]; }
        if (id == 6) { return [-1, 16777215, 16051939, 12434877, 9079434, 4868682, 13038642, 6021467, 7268279, 3003583, 11129855, 5088255, 8367840, 12170485, 16727461, 16743019, 16107173, 16754219, 16761370, 16769306, 16726862, 11747630, 2051679, 1780292, 1118481]; }
        if (id == 7) { return [-1, -10, 16777215, 16051939, 12434877, 9079434, 4868682, 13038642, 6021467, 7268279, 3003583, 11129855, 5088255, 8367840, 12170485, 16727461, 16743019, 16107173, 16754219, 16761370, 16769306, 16726862, 11747630, 2051679, 1780292, 1118481]; }
        return [];
    }
}
